name: WIDOCO build
on: [push]
jobs:
  widoco:
    runs-on: ubuntu-latest
    name: A conversion of ttl to html
    steps:
      - name: Debug repository contents
        run: |
          echo "Workspace:"
          pwd
      
          echo "Repository tree:"
          find /github/workspace -maxdepth 4 -type f
      - name: convert
        uses: soilwise-he/widoco-action@v0.3
        with:
          file-input: '/github/workspace/ontology/ontology.rdf'
          folder-output: '/github/workspace/ontology/doc'
          options: '-excludeProvenance -getOntologyMetadata'
